openapi: 3.0.0
info:
  title: Example API
  description: Sample description
  version: 1.0.0
paths:
  /boom:
    get:
      summary: Throws an error to be localised
      description: Example
      x-controller: boom
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
