openapi: 3.0.0
info:
  title: Example API3
  description: Sample description3
  version: 3.0.0
paths:
  /d3/example:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: v1/get
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
