openapi: 3.0.0
info:
  title: Example API
  description: Sample description
  version: 1.0.0
paths:
  /example-redis:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: example-redis/redis
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: object
  /example-memory:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: example-memory/memory
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /example-cacher:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: example-cacher/cacher
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /example-queue:
    post:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.

      x-controller: example-queue/queue
      tags:
        - Example
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              type: object

        required: true
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: object
