---
format_version: 3
pipelines:
  core-session-service-build-docker:
    group: core-session-service
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      NPM_CONF_REG: registry=https://artifactory.gamesys.co.uk/artifactory/api/npm/gamesys-unicorn-npm-virtual/
      NPM_CONF_AUTH_ALWAYS: always-auth=true
      MSTEAMS_URL: https://gamesys.webhook.office.com/webhookb2/9c45693c-b685-45e4-9a7e-a0222ad9e359@a2fb1bdc-71c6-43b3-b80d-de077d817707/IncomingWebhook/ae5dd4a9079a4e02a4de71960a9592c5/1ee6cfcf-2e3a-4a60-b0fe-0c463173716e
    secure_variables:
      NPM_USER: AES:OyTfPufSGNv+SSDu54xROw==:mPHBnbimJjnznW4qjq6Uy9FltA0iSB1NRe0Tg0g+Gek=
      NPM_PASS: AES:f5SpoI8+Y851I42DI52cCw==:QJEeyTubh5UVVA93VSc1lW4Pyk68Z+50YNEB975+U+Q=
      gocd_agent_artifactory_password: AES:naqOGANUbGSuSSFDUiYZwQ==:E/C0A1eeReF9TVW5WYKfmLzT9xaCyEIn7f6kHyQxDFs=
    materials:
      git:
        git: git@github.gamesys.co.uk:PlayerServices/core-session-service.git
        shallow_clone: false
        auto_update: true
        branch: master
      core-session-service-build:
        pipeline: core-session-service-build
        stage: build
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            build:
              timeout: 0
              environment_variables:
                LOG_CONSOLE: 'true'
                LOG_LEVEL: info
                LOG_PATH: winston.log
                PORT: 3000
              resources:
                - rpm
              artifacts:
                - build:
                    source: version.txt
                    destination: ''
              tasks:
                - fetch:
                    is_file: true
                    source: version.txt
                    destination: ''
                    pipeline: core-session-service-build
                    stage: build
                    job: build
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "npm config list\r\n\r\necho \"USER INFO\"\r\necho \"$NPM_CONF_REG\"\r\necho \"$NPM_CONF_AUTH_ALWAYS\"\r\n\r\necho \"$NPM_CONF_REG\" > .npmrc\r\necho \"$NPM_CONF_AUTH_ALWAYS\" >> .npmrc\r\necho \"//artifactory.gamesys.co.uk/artifactory/api/npm/gamesys-unicorn-npm-virtual/:_authToken=$(curl -u$NPM_USER:$NPM_PASS -XPOST \"https://artifactory.gamesys.co.uk/artifactory/api/security/token\" -d username=\"$NPM_USER\" -d \"scope=member-of-groups:*\" | jq -r '.access_token')\" >> .npmrc"
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "set -e\r\n\r\nBUILD_NUMBER=$(cat version.txt)\r\n\r\ndocker build -t #{repository}:${BUILD_NUMBER} .\r\ndocker push #{repository}:${BUILD_NUMBER}\r\ndocker rmi -f  #{repository}:${BUILD_NUMBER}"
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "if [ -n \"${MSTEAMS_URL}\" ]; then \
                           \r\n  docker login gamesys-ps-private-docker-build.artifactory.gamesys.co.uk \
                                 -u ps_incentive_automation_ci -p $gocd_agent_artifactory_password \
                           \r\n  docker run --rm --name \"notify_ci_${GO_PIPELINE_NAME}_${GO_STAGE_NAME}_${GO_JOB_NAME}_${GO_PIPELINE_COUNTER}\" -t \
                                 -e GOCD_OPERATION=\"notify_ci\" \
                                 -e GOCD_NOTIFY_CI_TYPE=\"GENERAL\" \
                                 -e GOCD_NOTIFY_CI_STATUS=\"FAILED\" \
                                 -e GOCD_NOTIFY_CI_GOCDURL=\"https://gocd.psunicorncd.pgt.gaia\" \
                                 -e GOCD_NOTIFY_CI_PIPELINENAME=\"${GO_PIPELINE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINELABEL=\"${GO_PIPELINE_LABEL}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINECOUNTER=\"${GO_PIPELINE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_STAGENAME=\"${GO_STAGE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_STAGECOUNTER=\"${GO_STAGE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_JOBNAME=\"${GO_JOB_NAME}\" \
                                 -e GOCD_NOTIFY_CI_TRIGGERUSER=\"${GO_TRIGGER_USER}\" \
                                 -e GOCD_MSTEAMS_URL=\"${MSTEAMS_URL}\" \
                                 gamesys-ps-private-docker-build.artifactory.gamesys.co.uk/boost/boost-gocd-tools:1.0 \
                           \r\nfi"
                    run_if: failed
    parameters:
      repository: unicorn-docker.artifactory.gamesys.co.uk/core-session-service
