---
format_version: 3
pipelines:
  core-session-service-create-release-ticket-az:
    group: core-session-service
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      is_automated_live: '-l true'
      deploy_env_flag: '-e live-usaz1'
      MSTEAMS_URL: https://gamesys.webhook.office.com/webhookb2/9c45693c-b685-45e4-9a7e-a0222ad9e359@a2fb1bdc-71c6-43b3-b80d-de077d817707/IncomingWebhook/ae5dd4a9079a4e02a4de71960a9592c5/1ee6cfcf-2e3a-4a60-b0fe-0c463173716e
    secure_variables:
      gocd_agent_artifactory_password: AES:naqOGANUbGSuSSFDUiYZwQ==:E/C0A1eeReF9TVW5WYKfmLzT9xaCyEIn7f6kHyQxDFs=
    materials:
      core-session-service-build-docker:
        pipeline: core-session-service-build-docker
        stage: build
    template: service-raise-ticket
    parameters:
      service_build_pipeline: core-session-service-build-docker
      component: core-session-service
