openapi: 3.0.0
info:
  title: Example API
  description: Sample description
  version: 1.0.0
paths:
  /example-os:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: example-os/os
      tags:
        - Example
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: object
