---
format_version: 3
pipelines:
  {{ generated_service_id }}-build:
    group: {{ generated_service_id }}
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      NPM_CONF_REG: registry=https://artifactory.gamesys.co.uk/artifactory/api/npm/gamesys-unicorn-npm-virtual/
      NPM_CONF_AUTH_ALWAYS: always-auth=true
      MSTEAMS_URL: https://gamesys.webhook.office.com/webhookb2/9c45693c-b685-45e4-9a7e-a0222ad9e359@a2fb1bdc-71c6-43b3-b80d-de077d817707/IncomingWebhook/ae5dd4a9079a4e02a4de71960a9592c5/1ee6cfcf-2e3a-4a60-b0fe-0c463173716e
    secure_variables:
      NPM_USER: AES:OyTfPufSGNv+SSDu54xROw==:mPHBnbimJjnznW4qjq6Uy9FltA0iSB1NRe0Tg0g+Gek=
      NPM_PASS: AES:f5SpoI8+Y851I42DI52cCw==:QJEeyTubh5UVVA93VSc1lW4Pyk68Z+50YNEB975+U+Q=
      gocd_agent_artifactory_password: AES:naqOGANUbGSuSSFDUiYZwQ==:E/C0A1eeReF9TVW5WYKfmLzT9xaCyEIn7f6kHyQxDFs=
    materials:
      git:
        git: git@github.gamesys.co.uk:PlayerServices/{{ generated_service_id }}.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            build:
              timeout: 0
              environment_variables:
                LOG_CONSOLE: 'true'
                LOG_LEVEL: info
                LOG_PATH: winston.log
                PORT: 3000
              resources:
                - docker
                - git
                - node
              artifacts:
                - build:
                    source: version.txt
                    destination: ''
              tasks:
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "DIFF=$(git diff --name-only yarn.lock)\r\nLOCK_FILE=\"yarn.lock\"\r\n\r\nif [[ $DIFF = $LOCK_FILE ]]; then\r\n    echo \"🚫 Packages build failed! 🚫\"\r\n    echo \"Reason: your yarn.lock file has changed\"\r\n    echo \"To fix: Please include the lock file changes in your latest commit\"\r\n    exit 1\r\nfi"
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: echo "$(node -p "require('./package.json').version")-$GO_PIPELINE_LABEL" > version.txt; cat version.txt
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "npm config list\r\n\r\necho \"USER INFO\"\r\necho \"$NPM_CONF_REG\"\r\necho \"$NPM_CONF_AUTH_ALWAYS\"\r\n\r\necho \"$NPM_CONF_REG\" > .npmrc\r\necho \"$NPM_CONF_AUTH_ALWAYS\" >> .npmrc\r\necho \"//artifactory.gamesys.co.uk/artifactory/api/npm/gamesys-unicorn-npm-virtual/:_authToken=$(curl -u$NPM_USER:$NPM_PASS -XPOST \"https://artifactory.gamesys.co.uk/artifactory/api/security/token\" -d username=\"$NPM_USER\" -d \"scope=member-of-groups:*\" | jq -r '.access_token')\" >> .npmrc"
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: yarn add semantic-release@17.3.8 @semantic-release/release-notes-generator@9.0.1 @semantic-release/npm@7.0.10 @semantic-release/git@9.0.0 @semantic-release/commit-analyzer@8.0.1 @semantic-release/changelog@5.0.1 --dev --frozen-lockfile --ignore-engines
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "git remote update\r\n\r\nUPSTREAM=${1:-'@{u}'}\r\nLOCAL=$(git rev-parse @{0})\r\nREMOTE=$(git rev-parse \"$UPSTREAM\")\r\n\r\nif [ $LOCAL = $REMOTE ]; then\r\n echo \"Publishing and updating Master\"\r\n    npx semantic-release --no-ci\r\n else\r\n\r\n echo \"The remote and local branch have diverged most likely due to a commit being added to remote master\"\r\r\n echo \"**NOT PUBLISHING**\"\r\r\n echo \"This job will retrigger with a batch of current and new changes\"\r \r\nfi"
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "if [ -n \"${MSTEAMS_URL}\" ]; then \
                           \r\n  docker login gamesys-ps-private-docker-build.artifactory.gamesys.co.uk \
                                 -u ps_incentive_automation_ci -p $gocd_agent_artifactory_password \
                           \r\n  docker run --rm --name \"notify_ci_${GO_PIPELINE_NAME}_${GO_STAGE_NAME}_${GO_JOB_NAME}_${GO_PIPELINE_COUNTER}\" -t \
                                 -e GOCD_OPERATION=\"notify_ci\" \
                                 -e GOCD_NOTIFY_CI_TYPE=\"GENERAL\" \
                                 -e GOCD_NOTIFY_CI_STATUS=\"FAILED\" \
                                 -e GOCD_NOTIFY_CI_GOCDURL=\"https://gocd.psunicorncd.pgt.gaia\" \
                                 -e GOCD_NOTIFY_CI_PIPELINENAME=\"${GO_PIPELINE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINELABEL=\"${GO_PIPELINE_LABEL}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINECOUNTER=\"${GO_PIPELINE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_STAGENAME=\"${GO_STAGE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_STAGECOUNTER=\"${GO_STAGE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_JOBNAME=\"${GO_JOB_NAME}\" \
                                 -e GOCD_NOTIFY_CI_TRIGGERUSER=\"${GO_TRIGGER_USER}\" \
                                 -e GOCD_MSTEAMS_URL=\"${MSTEAMS_URL}\" \
                                 gamesys-ps-private-docker-build.artifactory.gamesys.co.uk/boost/boost-gocd-tools:1.0 \
                           \r\nfi"
                    run_if: failed
