---
format_version: 3
pipelines:
  {{ generated_service_id }}-deploy-int09:
    group: {{ generated_service_id }}
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      MSTEAMS_URL: https://gamesys.webhook.office.com/webhookb2/9c45693c-b685-45e4-9a7e-a0222ad9e359@a2fb1bdc-71c6-43b3-b80d-de077d817707/IncomingWebhook/ae5dd4a9079a4e02a4de71960a9592c5/1ee6cfcf-2e3a-4a60-b0fe-0c463173716e
    secure_variables:
      password: AES:WxHsC14B7kIaX7KvEHB15A==:yCyOi/z4St8tVQmoZjpfZZ9YeqFIYxs3f2AimlbmUKY=
      gocd_agent_artifactory_password: AES:naqOGANUbGSuSSFDUiYZwQ==:E/C0A1eeReF9TVW5WYKfmLzT9xaCyEIn7f6kHyQxDFs=
    materials:
      {{ generated_service_id }}-build-docker:
        pipeline: {{ generated_service_id }}-build-docker
        stage: build
    stages:
      - deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            deploy:
              timeout: 0
              resources:
                - tower-cli
              tasks:
                - fetch:
                    is_file: true
                    source: version.txt
                    destination: ''
                    pipeline: {{ generated_service_id }}-build-docker
                    stage: build
                    job: build
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: 'tower-cli job launch -J "#{cc_template}" -h #{cc_address} -u PlayerServices-Unicorn-Provisioner -p ${password} -e "{\"app_version\": \"$(cat version.txt)\"}" -e "{\"deploy_env\": \"#{deploy_env}\"}" -e "{\"kubes_suffix\": \"\"}" --monitor --insecure'
                    run_if: passed
                - plugin:
                    configuration:
                      id: script-executor
                      version: '1'
                    options:
                      script: "if [ -n \"${MSTEAMS_URL}\" ]; then \
                           \r\n  docker login gamesys-ps-private-docker-build.artifactory.gamesys.co.uk \
                                 -u ps_incentive_automation_ci -p $gocd_agent_artifactory_password \
                           \r\n  docker run --rm --name \"notify_ci_${GO_PIPELINE_NAME}_${GO_STAGE_NAME}_${GO_JOB_NAME}_${GO_PIPELINE_COUNTER}\" -t \
                                 -e GOCD_OPERATION=\"notify_ci\" \
                                 -e GOCD_NOTIFY_CI_TYPE=\"GENERAL\" \
                                 -e GOCD_NOTIFY_CI_STATUS=\"FAILED\" \
                                 -e GOCD_NOTIFY_CI_GOCDURL=\"https://gocd.psunicorncd.pgt.gaia\" \
                                 -e GOCD_NOTIFY_CI_PIPELINENAME=\"${GO_PIPELINE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINELABEL=\"${GO_PIPELINE_LABEL}\" \
                                 -e GOCD_NOTIFY_CI_PIPELINECOUNTER=\"${GO_PIPELINE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_STAGENAME=\"${GO_STAGE_NAME}\" \
                                 -e GOCD_NOTIFY_CI_STAGECOUNTER=\"${GO_STAGE_COUNTER}\" \
                                 -e GOCD_NOTIFY_CI_JOBNAME=\"${GO_JOB_NAME}\" \
                                 -e GOCD_NOTIFY_CI_TRIGGERUSER=\"${GO_TRIGGER_USER}\" \
                                 -e GOCD_MSTEAMS_URL=\"${MSTEAMS_URL}\" \
                                 gamesys-ps-private-docker-build.artifactory.gamesys.co.uk/boost/boost-gocd-tools:1.0 \
                           \r\nfi"
                    run_if: failed
    parameters:
      deploy_env: int09
      cc_template: "{{ generated_service_id }} - int09 - V3"
      cc_address: https://controlcentre.int90.integration.pgt.gaia
