format_version: 3
pipelines:
  service-kit-build:
    group: Microservice_Libraries
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      git:
        git: git@github.gamesys.co.uk:PlayerServices/service-kit.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - service:
          fetch_materials: true
          clean_workspace: true
          keep_artifacts: false
          approval:
            type: success
          jobs:
            build-and-version:
              timeout: 0
              resources:
                - node18
              tasks:
                - exec:
                    arguments:
                      - -c
                      - yarn install
                    command: /bin/bash
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - yarn build
                    command: /bin/bash
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - yarn lintify
                    command: /bin/bash
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - "./node_modules/.bin/lerna publish --yes"
                    command: /bin/bash
                    run_if: passed
