openapi: 3.0.0
info:
  title: Example API
  description: Sample description
  version: 1.0.0
paths:
  /auth-middleware:
    get:
      summary: An authenticated middleware that uses chimera authentication
      description: Requires both memberid and authtoken
      x-controller: middlewareChimeraAuth
      x-member-auth-enabled: true
      x-member-auth-required: true
      parameters:
        - in: header
          name: client-memberid
          schema:
            type: string
          required: true
        - in: header
          name: client-authtoken
          schema:
            type: string
          required: true
      tags:
        - Example
      responses:
        "200":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth-service:
    get:
      summary: A route that uses standalone chimera auth service functionality
      description: Requires both memberid and authtoken
      x-controller: serviceChimeraAuth
      parameters:
        - in: header
          name: client-memberid
          schema:
            type: string
          required: true
        - in: header
          name: client-authtoken
          schema:
            type: string
          required: true
        # - name: Cookie
        #   in: header
        #   required: true
        #   schema:
        #     type: string
        #     pattern: '(.*test=.*)'
        #   description: Signifies a logged in member session id
      tags:
        - Example
      responses:
        "200":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: An example JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
components:
  schemas:
    Response:
      description: "Response"
      type: object
      required:
        - token
      properties:
        token:
          type: object
    Error:
      description: "Error"
      type: object
      required:
        - message
      properties:
        message:
          type: string
        details:
          type: object

          
