openapi: 3.0.0
info:
  title: example-service
  version: 3.0.0
  description: |-
    This is a Example Microservice API Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io). We've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features.
    Some useful links:
    - [The repository](https://github.gamesys.co.uk/PlayerServices/service-kit/tree/master/examples/core-versions)
    - [The source API definition](https://github.gamesys.co.uk/PlayerServices/service-kit/tree/master/examples/core-versions/src/contract)
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: PlayerServices/pegacorn

paths:
  /v3/example:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: v1/get
      tags:
        - Example V3
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /v3/example2:
    get:
      summary: Returns a bunch of dummy data.
      description: Optional extended description in CommonMark or HTML.
      x-controller: v1/get
      tags:
        - Example V3
      responses:
        "200": # status code
          description: A JSON array of dummy data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
