---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
  - include_role:
      name: deployment_k8s
  post_tasks:
  - include_role:
      name: update_consul
