---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: disable
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  line-length: disable
  key-duplicates: enable
  truthy: disable
