name: Lint yml on PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  yamllint:
    # The type of runner that the job will run on
    runs-on: [ unicorn ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs yamllint
      - name: Lint yaml files
        run: |
          cd $GITHUB_WORKSPACE \
          && echo Validating your yaml files \
          && yamllint -c yamllint-config.yml ./src ./deployment -f parsable

      # Clean up the workspace to make sure there is not leftover between runs, since we are using self-hosted runners that don't cleanup automatically.
      - name: Force cleanup workspace
        run: |
          echo "Cleaning up data from the run" \
          && cd $GITHUB_WORKSPACE \
          && rm -r *
