
name: Stress Test on PP via Proxy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      endpoint:
        description: 'The particular endpoint to load test :
          - * (for all)
          - health
          - gameConfig
        '
        default: 'health'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: [unicorn_load_test]
    env:
      # sets up proxy on the k6 docker container so we can hit ppc2
      HTTP_PROXY: 10.149.16.141:3546
      SELECTED_ENDPOINT: ${{github.event.inputs.endpoint}}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run k6 test
        uses: k6io/action@v0.1
        with:
          filename: test/load/stress_test.js
